config = {
    'teams_reddit': {
        "São Paulo": "saopaulofc",
        "Flamengo": "CRFla",
        "Palmeiras": "palmeiras",
        "Vasco": "vasco"
    },
    "setiment_mapping": {
        '5 stars': 'Positive',
        '4 stars': 'Positive',
        '3 stars': 'Neutral',
        '2 stars': 'Negative',
        '1 star': 'Negative'
    },
    "rodadas": {
        "Cruzeiro x Palmeiras": 38,
        "Palmeiras x Fluminense": 37,
        "Palmeiras x América-MG": 36,
        "Fortaleza x Palmeiras": 35,
        "Palmeiras x Internacional": 34,
        "Flamengo x Palmeiras": 33,
        "Palmeiras x Athletico-PR": 32,
        "Botafogo x Palmeiras": 31,
        "Palmeiras x Bahia": 30,
        "Palmeiras x São Paulo": 29,
        "Coritiba x Palmeiras": 28,
        "Palmeiras x Atlético-MG": 27,
        "Palmeiras x Santos": 26,
        "Bragantino x Palmeiras": 25,
        "Grêmio x Palmeiras": 24,
        "Palmeiras x Goiás": 23,
        "Corinthians x Palmeiras": 22,
        "Palmeiras x Vasco": 21,
        "Cuiabá x Palmeiras": 20,
        "Palmeiras x Cruzeiro": 19,
        "Fluminense x Palmeiras": 18,
        "América-MG x Palmeiras": 17,
        "Palmeiras x Fortaleza": 16,
        "Internacional x Palmeiras": 15,
        "Palmeiras x Flamengo": 14,
        "Athletico-PR x Palmeiras": 13,
        "Palmeiras x Botafogo": 12,
        "Bahia x Palmeiras": 11,
        "São Paulo x Palmeiras": 10,
        "Palmeiras x Coritiba": 9,
        "Atlético-MG x Palmeiras": 8,
        "Santos x Palmeiras": 7,
        "Palmeiras x Bragantino": 6,
        "Palmeiras x Grêmio": 5,
        "Goiás x Palmeiras": 4,
        "Palmeiras x Corinthians": 3,
        "Vasco x Palmeiras": 2,
        "Palmeiras x Cuiabá": 1,

        "Vasco x Bragantino": 38,
        "Grêmio x Vasco": 37,
        "Vasco x Corinthians": 36,
        "Athletico-PR x Vasco": 35,
        "Cruzeiro x Vasco": 33,
        "Vasco x América-MG": 34,
        "Vasco x Botafogo": 32,
        "Cuiabá x Vasco": 31,
        "Goiás x Vasco": 30,
        "Vasco x Internacional": 29,
        "Flamengo x Vasco": 28,
        "Vasco x Fortaleza": 27,
        "Vasco x São Paulo": 26,
        "Santos x Vasco": 25,
        "Vasco x Coritiba": 24,
        "Vasco x Fluminense": 23,
        "Bahia x Vasco": 22,
        "Vasco x Atlético-MG": 20,
        "Bragantino x Vasco": 19,
        "Vasco x Grêmio": 18,
        "Corinthians x Vasco": 17,
        "Vasco x Athletico-PR": 16,
        "América-MG x Vasco": 15,
        "Vasco x Cruzeiro": 14,
        "Botafogo x Vasco": 13,
        "Vasco x Cuiabá": 12,
        "Vasco x Goiás": 11,
        "Internacional x Vasco": 10,
        "Vasco x Flamengo": 9,
        "Fortaleza x Vasco": 8,
        "São Paulo x Vasco": 7,
        "Vasco x Santos": 6,
        "Coritiba x Vasco": 5,
        "Fluminense x Vasco": 4,
        "Vasco x Bahia": 3,
        "Atlético-MG x Vasco": 1,

        "São Paulo x Flamengo": 38,
        "Flamengo x Cuiabá": 37,
        "Flamengo x Atlético-MG": 36,
        "América-MG x Flamengo": 35,
        "Flamengo x Bragantino": 30,
        "Flamengo x Fluminense": 34,
        "Fortaleza x Flamengo": 32,
        "Flamengo x Santos": 31,
        "Grêmio x Flamengo": 29,
        "Cruzeiro x Flamengo": 27,
        "Corinthians x Flamengo": 26,
        "Flamengo x Bahia": 25,
        "Goiás x Flamengo": 24,
        "Flamengo x Athletico-PR": 23,
        "Botafogo x Flamengo": 22,
        "Flamengo x Internacional": 21,
        "Coritiba x Flamengo": 20,
        "Flamengo x São Paulo": 19,
        "Cuiabá x Flamengo": 18,
        "Atlético-MG x Flamengo": 17,
        "Flamengo x América-MG": 16,
        "Fluminense x Flamengo": 15,
        "Flamengo x Fortaleza": 13,
        "Santos x Flamengo": 12,
        "Bragantino x Flamengo": 11,
        "Flamengo x Grêmio": 10,
        "Flamengo x Cruzeiro": 8,
        "Flamengo x Corinthians": 7,
        "Bahia x Flamengo": 6,
        "Flamengo x Goiás": 5,
        "Athletico-PR x Flamengo": 4,
        "Flamengo x Botafogo": 3,
        "Internacional x Flamengo": 2,
        "Flamengo x Coritiba": 1,

        "Atlético-MG x São Paulo": 37,
        "Bahia x São Paulo": 36,
        "São Paulo x Cuiabá": 35,
        "Fluminense x São Paulo": 32,
        "Santos x São Paulo": 34,
        "São Paulo x Bragantino": 33,
        "São Paulo x Cruzeiro": 31,
        "Athletico-PR x São Paulo": 30,
        "São Paulo x Grêmio": 28,
        "Goiás x São Paulo": 27,
        "São Paulo x Corinthians": 25,
        "São Paulo x Coritiba": 22,
        "São Paulo x Fortaleza": 24,
        "Internacional x São Paulo": 23,
        "América-MG x São Paulo": 21,
        "São Paulo x Botafogo": 20,
        "São Paulo x Atlético-MG": 18,
        "São Paulo x Bahia": 17,
        "Cuiabá x São Paulo": 16,
        "São Paulo x Santos": 15,
        "Bragantino x São Paulo": 14,
        "São Paulo x Fluminense": 13,
        "Cruzeiro x São Paulo": 12,
        "São Paulo x Athletico-PR": 11,
        "Grêmio x São Paulo": 9,
        "São Paulo x Goiás": 8,
        "Corinthians x São Paulo": 6,
        "Fortaleza x São Paulo": 5,
        "São Paulo x Internacional": 4,
        "Coritiba x São Paulo": 3,
        "São Paulo x América-MG": 2,
        "Botafogo x São Paulo": 1
    }
     
}